{% set version = '14.1.0' %}
{% set name = 'ripgrep' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/BurntSushi/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 33c6169596a6bbfdc81415910008f26e0809422fda2d849562637996553b2ab6

build:
  number: 0
  script:
    - set RUST_BACKTRACE=1  # [win]
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo build --release -v
    - $STRIP target/release/rg  # [not win]
    - mkdir $PREFIX/bin  # [not win]
    - mkdir %PREFIX%\Library\mingw-w64\bin  # [win]
    - cp target/release/rg $PREFIX/bin/rg  # [not win]
    - copy target\release\rg.exe %PREFIX%\Library\mingw-w64\bin\rg.exe  # [win]
  missing_dso_whitelist:
    - $RPATH/ld64.so.1  # [s390x]

requirements:
  build:
    - {{ compiler('rust') }}  # [not win]
    - {{ compiler('rust-gnu') }}  # [win]
    - cargo-bundle-licenses

test:
  commands:
    - rg --version

about:
  home: https://github.com/BurntSushi/ripgrep
  dev_url: https://github.com/BurntSushi/ripgrep
  doc_url: https://github.com/BurntSushi/ripgrep
  summary: ripgrep recursively searches directories for a regex pattern while respecting your gitignore
  description: |
    ripgrep is a line-oriented search tool that recursively searches the current directory for a regex pattern.
  license: MIT AND Unlicense
  license_family: Other
  license_file:
    - LICENSE-MIT
